{
  "trials": 3,
  "cases": [
    "attacks.instances.cc_whitebox:CCWhitebox001",
    "attacks.instances.cc_whitebox:CCWhitebox002",
    "attacks.instances.cc_whitebox:CCWhitebox003",
    "attacks.instances.cc_whitebox:CCWhitebox004",
    "attacks.instances.cc_whitebox:CCWhitebox005",
    "attacks.instances.cc_whitebox:CCWhitebox006",
    "attacks.instances.cc_whitebox:CCWhitebox007",
    "attacks.instances.cc_whitebox:CCWhitebox008",
    "attacks.instances.cc_whitebox:CCWhitebox009",
    "attacks.instances.cc_whitebox:CCWhitebox010",
    "attacks.instances.cc_whitebox:CCWhitebox011",
    "attacks.instances.cc_whitebox:CCWhitebox012",
    "attacks.instances.cc_whitebox:CCWhitebox013",
    "attacks.instances.cc_whitebox:CCWhitebox014",
    "attacks.instances.cc_whitebox:CCWhitebox015",
    "attacks.instances.cc_whitebox:CCWhitebox016",
    "attacks.instances.cc_whitebox:CCWhitebox017",
    "attacks.instances.cc_whitebox:CCWhitebox018",
    "attacks.instances.cc_whitebox:CCWhitebox019",
    "attacks.instances.cc_whitebox:CCWhitebox020",
    "attacks.instances.cc_whitebox:CCWhitebox021",
    "attacks.instances.cc_whitebox:CCWhitebox022",
    "attacks.instances.cc_whitebox:CCWhitebox023",
    "attacks.instances.cc_whitebox:CCWhitebox024",
    "attacks.instances.cc_whitebox:CCWhitebox025",
    "attacks.instances.cc_whitebox:CCWhitebox026",
    "attacks.instances.cc_whitebox:CCWhitebox027",
    "attacks.instances.cc_whitebox:CCWhitebox028",
    "attacks.instances.cc_whitebox:CCWhitebox029",
    "attacks.instances.cc_whitebox:CCWhitebox030",
    "attacks.instances.cc_whitebox:CCWhitebox031",
    "attacks.instances.cc_whitebox:CCWhitebox032",
    "attacks.instances.cc_whitebox:CCWhitebox033",
    "attacks.instances.cc_whitebox:CCWhitebox034",
    "attacks.instances.cc_whitebox:CCWhitebox035",
    "attacks.instances.cc_whitebox:CCWhitebox036",
    "attacks.instances.cc_whitebox:CCWhitebox037",
    "attacks.instances.cc_whitebox:CCWhitebox038",
    "attacks.instances.cc_whitebox:CCWhitebox039",
    "attacks.instances.cc_whitebox:CCWhitebox040",
    "attacks.instances.cc_whitebox:CCWhitebox041",
    "attacks.instances.cc_whitebox:CCWhitebox042",
    "attacks.instances.cc_whitebox:CCWhitebox043",
    "attacks.instances.cc_whitebox:CCWhitebox044",
    "attacks.instances.cc_whitebox:CCWhitebox045",
    "attacks.instances.cc_whitebox:CCWhitebox046",
    "attacks.instances.cc_whitebox:CCWhitebox047",
    "attacks.instances.cc_whitebox:CCWhitebox048",
    "attacks.instances.cc_whitebox:CCWhitebox049",
    "attacks.instances.cc_whitebox:CCWhitebox050",
    "attacks.instances.cc_whitebox:CCWhitebox051",
    "attacks.instances.cc_whitebox:CCWhitebox052",
    "attacks.instances.cc_whitebox:CCWhitebox053",
    "attacks.instances.cc_whitebox:CCWhitebox054",
    "attacks.instances.cc_whitebox:CCWhitebox055",
    "attacks.instances.cc_whitebox:CCWhitebox056",
    "attacks.instances.cc_whitebox:CCWhitebox057",
    "attacks.instances.cc_whitebox:CCWhitebox058",
    "attacks.instances.cc_whitebox:CCWhitebox059",
    "attacks.instances.cc_whitebox:CCWhitebox060",
    "attacks.instances.cc_whitebox:CCWhitebox061",
    "attacks.instances.cc_whitebox:CCWhitebox062",
    "attacks.instances.cc_whitebox:CCWhitebox063",
    "attacks.instances.cc_whitebox:CCWhitebox064",
    "attacks.instances.cc_whitebox:CCWhitebox065",
    "attacks.instances.cc_whitebox:CCWhitebox066",
    "attacks.instances.cc_whitebox:CCWhitebox067",
    "attacks.instances.cc_whitebox:CCWhitebox068",
    "attacks.instances.cc_whitebox:CCWhitebox069",
    "attacks.instances.cc_whitebox:CCWhitebox070",
    "attacks.instances.cc_whitebox:CCWhitebox071",
    "attacks.instances.cc_whitebox:CCWhitebox072",
    "attacks.instances.cc_whitebox:CCWhitebox073",
    "attacks.instances.cc_whitebox:CCWhitebox074",
    "attacks.instances.cc_whitebox:CCWhitebox075",
    "attacks.instances.cc_whitebox:CCWhitebox076",
    "attacks.instances.cc_whitebox:CCWhitebox077",
    "attacks.instances.cc_whitebox:CCWhitebox078",
    "attacks.instances.cc_whitebox:CCWhitebox079",
    "attacks.instances.cc_whitebox:CCWhitebox080",
    "attacks.instances.cc_whitebox:CCWhitebox081",
    "attacks.instances.cc_whitebox:CCWhitebox082",
    "attacks.instances.cc_whitebox:CCWhitebox083",
    "attacks.instances.cc_whitebox:CCWhitebox084",
    "attacks.instances.cc_whitebox:CCWhitebox085",
    "attacks.instances.cc_whitebox:CCWhitebox086",
    "attacks.instances.cc_whitebox:CCWhitebox087",
    "attacks.instances.cc_whitebox:CCWhitebox088",
    "attacks.instances.cc_whitebox:CCWhitebox089",
    "attacks.instances.cc_whitebox:CCWhitebox090",
    "attacks.instances.cc_whitebox:CCWhitebox091",
    "attacks.instances.cc_whitebox:CCWhitebox092",
    "attacks.instances.cc_whitebox:CCWhitebox093",
    "attacks.instances.cc_whitebox:CCWhitebox094",
    "attacks.instances.cc_whitebox:CCWhitebox095",
    "attacks.instances.cc_whitebox:CCWhitebox096",
    "attacks.instances.cc_whitebox:CCWhitebox097",
    "attacks.instances.cc_whitebox:CCWhitebox098",
    "attacks.instances.cc_whitebox:CCWhitebox099",
    "attacks.instances.cc_whitebox:CCWhitebox100"
  ],
  "sut": {
    "comparator": "sut.cc.whitebox_static_comparator:WhiteboxStaticComparator",
    "kwargs": {}
  }
}
